three

diff --git a/.github/workflows/github.yml b/.github/workflows/github.yml
--- a/.github/workflows/github.yml
+++ b/.github/workflows/github.yml
@@ -66,22 +66,22 @@ jobs:
         run: |
           cd product  
           go test ./...
-  deploy:
-    runs-on: ubuntu-latest
-    needs: test
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+ deploy:
+  runs-on: ubuntu-latest
+  needs: test
+  steps:
+    - name: Checkout code
+      uses: actions/checkout@v3
 
-      - name: Set up SSH key
-        run: |
-          mkdir -p ~/.ssh
-          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
-          ls -l ~/.ssh
-          cat ~/.ssh/id_ed25519 || echo "Key file not found"
-          chmod 600 ~/.ssh/id_ed25519
-          
-          # Start SSH agent and add key
-          eval $(ssh-agent -s)
-          ssh-add ~/.ssh/id_ed25519 || { echo "Failed to add SSH key"; exit 1; }
-          ssh-add -l || { echo "No keys added"; exit 1; }
+    - name: Set up SSH key
+      run: |
+        mkdir -p ~/.ssh
+        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
+        ls -l ~/.ssh
+        head -n 10 ~/.ssh/id_rsa
+        chmod 600 ~/.ssh/id_rsa
+        
+        # Start SSH agent and add key
+        eval $(ssh-agent -s)
+        ssh-add ~/.ssh/id_rsa || { echo "Failed to add SSH key"; exit 1; }
+        ssh-add -l || { echo "No keys added"; exit 1; }
